version: '2'
services:
  pro-_PROJECT_NAME_.emergyalabs.com:
    image: ${DOCKER_IMAGE}
    ports:
      - "22122:22"
      - "80:80"
      - "443:443"
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - DEVELOPER_USER=${DEVELOPER_USER}
      - LOCALES=es_ES.UTF-8 en_US.UTF-8
      - PROJECT_NAME=${PROJECT_NAME}
      - ENVIRONMENT=${ENVIRONMENT}
      - ENV_VHOST=${ENV_VHOST}
      - VIRTUAL_HOSTS=${VIRTUAL_HOSTS}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - MEMCACHED_PORT=${MEMCACHED_PORT}
    volumes:
      - ${HOME}/.drush:${HOME}/.drush
      - ${SSH_CREDENTIALS_DIR}:${SSH_CREDENTIALS_DIR}
      - ${PROJECT_DIR}:${PROJECT_DIR}
      - ${PROJECT_DIR}/src:/var/www/html
      - ${DATA_DIR}:/data
      - /opt/data/docker-containers-volumes/${DRUPAL_ROOT}/sites/default/private:${DRUPAL_ROOT}/sites/default/private
      - /opt/data/docker-containers-volumes/${DRUPAL_ROOT}/sites/default/files:${DRUPAL_ROOT}/sites/default/files
      - /opt/data/docker-containers-volumes/var/log/apache2:/var/log/apache2
      - /opt/data/docker-containers-volumes/etc/apache2/htpasswd/env-htpasswd:/etc/apache2/htpasswd/env-htpasswd
      - /opt/data/docker-containers-volumes/var/lib/mysql:/var/lib/mysql
